core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('registry.urls')),
    path('contribute/', include('contribute.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registry/urls.py
from django.urls import path

from .views import (
    index, 

    explore_startups,
    startup_category_detail,
    startup_development_stage_detail,
    startup_funding_stage_detail,

    explore_organizations,
    organization_type_detail,
    
    explore_programs,
    startup_support_program_detail,

    show_404
)

app_name = 'registry'

urlpatterns = [
    path('', index, name='index'),
    
    path('explore/startups', explore_startups, name='explore-startups'),
    path('explore/startups/spheres/<slug:slug>', startup_category_detail, name='startup-category-detail'),
    path('explore/startups/dev-stages/<slug:slug>', startup_development_stage_detail, name='startup-development-stage-detail'),
    path('explore/startups/funding-stages/<slug:slug>', startup_funding_stage_detail, name='startup-funding-stage-detail'),
    
    path('explore/organizations', explore_organizations, name='explore-organizations'),
    path('explore/organizations/<slug:slug>/', organization_type_detail, name='organization-type-detail'),
    
    path('explore/programs', explore_programs, name='explore-programs'),
    path('explore/programs/type/<slug:slug>/', startup_support_program_detail, name='startup-support-program-detail'),

    path('404', show_404, name='not-found')
]

notifications/models.py
from django.db import models

# Create your models here.
class SiteNotification(models.Model):
    title = models.CharField(max_length=255, verbose_name="Notification Title")
    message = models.TextField()

    show = models.BooleanField(default=True, verbose_name="Show Notification")
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if self.show:
            SiteNotification.objects.exclude(pk=self.pk).filter(show=True).update(show=False)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Site Notification"
        verbose_name_plural = "Site Notifications"
        ordering = ['-created_at']  # Newest notifications first



class CTAMessage(models.Model):
    message = models.TextField(verbose_name="CTA Message")
    link_text = models.CharField(max_length=500, blank=True, null=True, verbose_name="CTA Link Text")
    link = models.CharField(max_length=500, blank=True, null=True, verbose_name="CTA Link")
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    show = models.BooleanField(default=True, verbose_name="Show CTA Message")
    
    def __str__(self):
        return self.message[:50]  # Return first 50 characters of the message
    

    def save(self, *args, **kwargs):
        if self.show:
            CTAMessage.objects.exclude(pk=self.pk).filter(show=True).update(show=False)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "CTA Message"
        verbose_name_plural = "CTA Messages"
        ordering = ['-created_at']  # Newest messages first

notifications/views.py
from django.shortcuts import render

# Create your views here.

templates/includes/bottom-promotion.html
{% load notification_tags %}

{% get_active_cta as cta %}
{% if cta %}
<section class="bottom-promotion">
    <p class="text-semibold">{{ cta.message }}.  <a class="text-semibold promotion-link" href="{{ cta.link }}" target="_blank"> {{ cta.link_text }} &#8594;</a></p>
</section>
{% endif %}

templates/includes/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Startup Guide</title>
    <meta name="description" content="A comprehensive guide to the startup ecosystem, featuring resources, programs, and insights to help entrepreneurs, investors, and innovators succeed. Discover startup opportunities, connect with the community, and grow your business.">
    <meta name="keywords" content="starup, startup guide, startup ecosystem, startup database">
    <meta name="author" content="Startup Guide">
    
    <!-- Canonical URL -->
    <link rel="canonical" href="https://startupguide.uz/">
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/site.webmanifest' %}">
    
    <link
        href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>

templates/includes/navbar.html
{% load static %}

<header class="section header">
    <a href="/"><h1 class="logo-text heading-extrabold">Startup <span>Guide</span></h1></a>

    <nav class="nav">
        <ul>
            <li class="nav-item with-icon">
                <a class="heading-regular" href="https://t.me/startup_guide_uz" target="_blank"><img src="{% static 'images/tg_icon.png'%}" alt="Telegram Icon"></a>
            </li>
        </ul>
    </nav>
</header>

templates/includes/notification.html
{% load notification_tags %}

{% get_notification as notification %}
{% if notification %}
    <section class="section">
        <p class="notification-message text-light">{{ notification.message }}</p>    
    </section>
{% endif %}

templates/includes/subnav.html
{% load i18n %}

{% load stage_tags %}

<section class="section">
    <div class="menu-container">
        <ul class="menu">
            <li class="menu-item">
                <a class="text-regular list-item-title {% if request.resolver_match.url_name == 'explore-programs' %}menu-item-active text-semibold{% endif %}" href="{% url 'registry:explore-programs' %}">{% trans 'Support Programs' %}</a><span class="menu-item-counter  text-semibold">{% get_all_support_program_count %}</span></li>
            <li class="menu-item"><a class="text-regular list-item-title {% if request.resolver_match.url_name == 'explore-startups' %}menu-item-active  text-semibold{% endif %}" href="{% url 'registry:explore-startups' %}">{% trans 'Startups' %}</a><span class="menu-item-counter  text-semibold">{% get_all_startup_count %}</span></li>
            <li class="menu-item"><a class="text-regular list-item-title {% if request.resolver_match.url_name == 'explore-organizations' %}menu-item-active  text-semibold{% endif %}" href="{% url 'registry:explore-organizations' %}">{% trans 'Organizations' %}</a><span class="menu-item-counter  text-semibold">{% get_all_organization_count %}</span></li>
        </ul>
    </div>
</section>